### ISSUE TITLE
Data loss with acquisition in 5 channels

### ISSUE THREAD

**Issue by mariambrites** [scientisst/scientisst-sense-api-python#2]
When data is acquired from 5 channels with sampling frequency of 100Hz or higher, NSeq is not in the correct order. With 10Hz sampling frequency or acquisition in only one channel there is no problem.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/91912476/143619724-a07825c4-fd76-4c95-b888-9b5261e4feab.png">

**Comment by afonsocraposo** [comment]
Could not reproduce the error with my current setup:
- firmware - https://github.com/scientisst/scientisst-sense-firmware/commit/049c7e620f0fe246cccd406785762f7089355889
- api - https://github.com/scientisst/scientisst-sense-api-python/commit/c31b404cd6de3167b2a414df749ea9776d60511b
Maybe it is a device-specific problem (?)
